project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Malone Disturbance Ecology Lab: Onboarding"
  repo-url: https://github.com/Malone-Disturbance-Ecology-Lab/Onboarding
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Setup"
        menu: 
          - href: installation.qmd
            text: "Installation"
          - href: workflow.qmd
            text: "Git Workflow"
          - href: server.qmd
            text: "MaloneLab Server"
      - text: "Best Practices"
        menu:
          - href: where_to_put_data.qmd
            text: "Where to Put Data"
          - href: file_paths.qmd
            text: "File Paths"
          - href: readme.qmd
            text: "README help"
            
    right: 
      - icon: github
        href: https://github.com/Malone-Disturbance-Ecology-Lab/Onboarding
  page-footer: 
    center: "Copyright &copy; 2026, Sparkle Malone"
    background: secondary

format:
  html:
    theme: 
       - sandstone
       - custom_theme.scss
    mainfont: "Gill Sans"
    toc: true
    link-external-newwindow: true
    link-external-icon: false
