---
title: "README Help"
---

The README is a great place to write a summary of your project objectives, folders, workflows, and any other information that would be important for others to know about your project. GitHub repos will automatically display the README at the landing page of your repo so it will be the first thing that everyone sees about your project. It's well worth the time to update the README regularly,

If you didn't check the option to create a README during repo initialization, you can always create one at any time by going to the repo landing page on GitHub then **Add File** --> **Create New File** --> name the file "README.md". Or you can also name it "README.Rmd" if you want your README to run R code.

READMEs will look different depending on the type of project. Check out the different README examples below for a...

- personal research project: [https://github.com/jnawang/thermal_acclimation_in_ecosystem_respiration](https://github.com/jnawang/thermal_acclimation_in_ecosystem_respiration) 
- synthesis working group: [https://github.com/lter/lterwg-flux-gradient](https://github.com/lter/lterwg-flux-gradient)
- R package: [https://github.com/Malone-Disturbance-Ecology-Lab/ERA5Flux](https://github.com/Malone-Disturbance-Ecology-Lab/ERA5Flux)

In general, consider adding these to your README if applicable:

- Repo purpose
   - Write a summary of the purpose of your repo. What is the project you're doing? What is the rationale behind it? 
- Repo structure or folder organization
   - If you have sub-folders in your repo (and you should!), you should explain what each folder is for so that users visiting your repo will understand how your work is organized. You may even "draw" a directory structure like so:

```
my_project/
├── functions/               # Core analysis functions
│   ├── summarize_data.R             
│   └── plot_results.R             
│
├── workflows/               # Complete analysis workflows
│   ├── data_download.R   
│   ├── data_prep.R        
│   └── data_analysis.R             
│
├── exploratory/             # Preliminary analyses and development
│   └── ...
│
└── deprecated/              # Unused workflows and functions
```
- Script explanations
   - Write short descriptions of what your scripts do. If you anticipate that your workflow will involve many inputs and outputs, you can list the inputs and outputs of each script to keep track of the moving parts.
- Details on accessing external data required for workflow (if any)
   - Make sure to include any necessary links if needed.
- Instructions on downloading special software required for workflow (if any)
   - For example, if your workflow requires software hosted only on GitHub, you can include the code to download that software.
- References or acknowledgments 
   - Give credit where credit is due. 
